### PR TITLE
Fix rust-src prefix on windows.

### LINKED ISSUE #143: rust-src has a wrong install prefix.
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Rust-src should be installed at $MAMBA_ROOT_PREFIX/Library. 
After I installed rust-src on windows, I still get "Is rust-src installed? can't load standard library from sysroot" from the rust-analyzer extension in vscode.

### Installed packages

```shell
bzip2                            1.0.8         h8ffe710_4          conda-forge
  ca-certificates                  2023.5.7      h56e8100_0          conda-forge
  gettext                          0.21.1        h5728263_0          conda-forge
  git                              2.40.1        h57928b3_0          conda-forge
  libexpat                         2.5.0         h63175ca_1          conda-forge
  libffi                           3.4.2         h8ffe710_5          conda-forge
  libiconv                         1.17          h8ffe710_0          conda-forge
  libsqlite                        3.40.0        hcfcfb64_1          conda-forge
  libzlib                          1.2.13        hcfcfb64_4          conda-forge
  micromamba                       1.4.2         2                   conda-forge
  openssl                          3.1.0         hcfcfb64_3          conda-forge
  pip                              23.1.2        pyhd8ed1ab_0        conda-forge
  python                           3.11.3        h2628c8c_0_cpython  conda-forge
  python_abi                       3.11          3_cp311             conda-forge
  rust                             1.69.0        hf8d6059_2          conda-forge
  rust-src                         1.69.0        hd8ed1ab_2          conda-forge
  rust-std-x86_64-pc-windows-msvc  1.69.0        h69312b4_2          conda-forge
  setuptools                       67.7.2        pyhd8ed1ab_0        conda-forge
  starship                         1.14.2        hd956f44_0          conda-forge
  tk                               8.6.12        h8ffe710_0          conda-forge
  tzdata                           2023c         h71feb2d_0          conda-forge
  ucrt                             10.0.22621.0  h57928b3_0          conda-forge
  vc                               14.3          h3d8a991_11         conda-forge
  vc14_runtime                     14.34.31931   h5081d32_16         conda-forge
  vim                              9.0.1425      py311h12c1d0e_0     conda-forge
  vs2015_runtime                   14.34.31931   hed1258a_16         conda-forge
  wheel                            0.40.0        pyhd8ed1ab_0        conda-forge
  xz                               5.2.6         h8d14728_0          conda-forge
```

### Environment info

```shell
environment : base (active)
           env location : C:\Users\stray\Local\umamba
      user config files : C:\Users\stray\.mambarc
 populated config files : C:\Users\stray\.condarc
       libmamba version : 1.4.2
     micromamba version : 1.4.2
           curl version : libcurl/7.86.0-DEV Schannel zlib/1.2.13
     libarchive version : libarchive 3.6.1 zlib/1.2.13 liblzma/5.4.0 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __win=0=0
                          __archspec=1=x86_64
                          __cuda=11.7=0
               channels : https://mirrors.nju.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.nju.edu.cn/anaconda/cloud/conda-forge/noarch
       base environment : C:\Users\stray\Local\umamba
               platform : win-64
```

### PR DESCRIPTION
**Pull request by dingdang66686**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #143

### CODE REVIEW

**Comment by dingdang66686** [comment]
@conda-forge-admin, please rerender

**Comment by dingdang66686** [comment]
@conda-forge-admin, please rerender

File: recipe/install-rust-src.sh [hunk 1]
```diff
@@ -4,9 +4,11 @@ set -ex
...
 ./install.sh --prefix="$PREFIX" --destdir="$DESTDIR"
 
-rm "${PREFIX}"/lib/rustlib/components
-rm "${PREFIX}"/lib/rustlib/install.log
-rm "${PREFIX}"/lib/rustlib/rust-installer-version
-rm "${PREFIX}"/lib/rustlib/uninstall.sh
+rm "${DESTDIR}"/"${PREFIX}"/lib/rustlib/components
+rm "${DESTDIR}"/"${PREFIX}"/lib/rustlib/install.log
+rm "${DESTDIR}"/"${PREFIX}"/lib/rustlib/rust-installer-version
+rm "${DESTDIR}"/"${PREFIX}"/lib/rustlib/uninstall.sh
```
Comment (pkgw) [inline recipe/install-rust-src.sh:14]: Are the changes to this file necessary? If we are just setting `$DESTDIR` to `/`, it seems to me that this file does not need to be modified.

File: recipe/install-rust-src.bat [hunk 2]
```diff
@@ -0,0 +1,8 @@
+set MSYSTEM=MINGW%ARCH%
+set MSYS2_PATH_TYPE=inherit
+set CHERE_INVOKING=1
+FOR /F "delims=" %%i in ('cygpath.exe -u "%PREFIX%"') DO set "PREFIX=%%i/Library"
+FOR /F "delims=" %%i in ('cygpath.exe -u "%SRC_DIR%"') DO set "SRC_DIR=%%i"
+copy "%RECIPE_DIR%\install-rust-src.sh" .
```
Comment (pkgw) [inline recipe/install-rust-src.bat:6]: Is this `copy` statement necessary?

File: recipe/meta.yaml [hunk 3]
```diff
@@ -126,21 +126,28 @@ outputs:
         - echo {{ rust_arch }}
 
   - name: rust-src
-    script: install-rust-src.sh
+    script: install-rust-src.sh  # [unix]
+    script: install-rust-src.bat  # [win]
     build:
-      noarch: generic
-      skip: {{ rust_arch != "x86_64-unknown-linux-gnu" }}
+      skip: false
```
Comment (pkgw) [inline recipe/meta.yaml:132]: Ah, it is too bad that we are losing the `noarch`-ness of the `rust-src` package.

**Review by pkgw — COMMENTED** [review]
As I remark below, it is too bad that the `rust-src` package would have to lose its `noarch` status, but my interpretation of #143 is that this probably can't be avoided. Unless maybe there is some way to configure our `rust` package on Windows to point the analyzer at a non-standard prefix for the source code, or something?

File: recipe/install-rust-src.bat (hunk 2 above)
Comment (dingdang66686) [reply recipe/install-rust-src.bat:6]: I just copied these lines from install-rust.bat and it works.  😂

File: recipe/install-rust-src.sh (hunk 1 above)
Comment (dingdang66686) [reply recipe/install-rust-src.sh:14]: Yes, these changes are not necessary. But I think it's a better implementation because if you want to change DESTDIR and this is good to go.

File: recipe/meta.yaml (hunk 3 above)
Comment (dingdang66686) [reply recipe/meta.yaml:132]: I’m sorry too. This is the simplest solution I can think of right now. If you have a better idea, please feel free to share it.

**Review by pkgw — APPROVED** [review]
Thanks for improving the noarch-ness @isuruf! Anyone else on @conda-forge/rust have any comments?
